Update
(Logical change 1.283)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1034,15 +1034,18 @@ Optional Features:
                           build shared libraries [default=yes]
   --enable-static[=PKGS]
                           build static libraries [default=yes]
-  --enable-debug          enable debugging
-  --enable-really-static  completely static binaries
+  --enable-debug          enable additional debugging code and output
+  --disable-default-device-io-ops
+                          do not provide default device io operations
+  --disable-gnome-vfs     omit Gnome-VFS-2.0 'libntfs' interface
+                          (default=detect)
+  --enable-really-static  create completely static binaries for the utilities
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --disable-largefile     omit support for large files
-  --disable-gnome-vfs     Omit Gnome-VFS-2.0 'libntfs' interface (default=detect)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -2067,6 +2070,30 @@ else
 
 fi;
 
+# AH_TEMPLATE is needed here because we want to have a template in config.h
+# regardless of whether the option is given or not.
+
+
+# Check whether --enable-default-device-io-ops or --disable-default-device-io-ops was given.
+if test "${enable_default_device_io_ops+set}" = set; then
+  enableval="$enable_default_device_io_ops"
+  if test "$enable_default_device_io_ops" == "no"; then
+		cat >>confdefs.h <<\_ACEOF
+#define NO_NTFS_DEVICE_DEFAULT_IO_OPS 1
+_ACEOF
+
+	fi
+fi;
+
+# Check whether --enable-gnome-vfs or --disable-gnome-vfs was given.
+if test "${enable_gnome_vfs+set}" = set; then
+  enableval="$enable_gnome_vfs"
+
+else
+  enable_gnome_vfs=auto
+
+fi;
+
 # Check whether --enable-really-static or --disable-really-static was given.
 if test "${enable_really_static+set}" = set; then
   enableval="$enable_really_static"
@@ -2075,7 +2102,6 @@ else
   enable_really_static=no
 
 fi;
-
 
 
 if test "$enable_really_static" = yes; then
@@ -3760,7 +3786,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3763 "configure"' > conftest.$ac_ext
+  echo '#line 3789 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5257,7 +5283,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5260:" \
+echo "$as_me:5286:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6262,11 +6288,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6265: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6291: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6269: \$? = $ac_status" >&5
+   echo "$as_me:6295: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6494,11 +6520,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6497: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6523: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6501: \$? = $ac_status" >&5
+   echo "$as_me:6527: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6561,11 +6587,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6564: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6590: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6568: \$? = $ac_status" >&5
+   echo "$as_me:6594: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8580,7 +8606,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8583 "configure"
+#line 8609 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8678,7 +8704,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8681 "configure"
+#line 8707 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10810,11 +10836,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10813: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10839: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10817: \$? = $ac_status" >&5
+   echo "$as_me:10843: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10877,11 +10903,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10880: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10906: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10884: \$? = $ac_status" >&5
+   echo "$as_me:10910: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12127,7 +12153,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12130 "configure"
+#line 12156 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12225,7 +12251,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12228 "configure"
+#line 12254 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13047,11 +13073,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13050: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13076: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13054: \$? = $ac_status" >&5
+   echo "$as_me:13080: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13114,11 +13140,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13117: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13143: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13121: \$? = $ac_status" >&5
+   echo "$as_me:13147: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15061,11 +15087,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15064: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15090: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15068: \$? = $ac_status" >&5
+   echo "$as_me:15094: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15293,11 +15319,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15296: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15322: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15300: \$? = $ac_status" >&5
+   echo "$as_me:15326: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15360,11 +15386,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15363: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15389: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15367: \$? = $ac_status" >&5
+   echo "$as_me:15393: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17379,7 +17405,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17382 "configure"
+#line 17408 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17477,7 +17503,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17480 "configure"
+#line 17506 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18795,14 +18821,7 @@ rm -f conftest*
 fi
 
 
-# Check whether --enable-gnome-vfs or --disable-gnome-vfs was given.
-if test "${enable_gnome_vfs+set}" = set; then
-  enableval="$enable_gnome_vfs"
-
-else
-  enable_gnome_vfs=auto
-
-fi;
+# Autodetect whether to build Gnome VFS or not.
 compile_gnome_vfs=false
 if test "$enable_gnome_vfs" != "no"; then
 	# Make compilation work on SuSE 9.0.
@@ -18904,12 +18923,12 @@ echo "${ECHO_T}$LIBNTFS_GNOMEVFS_LIBS" >&6
   else
 
 		if test "$enable_gnome_vfs" = "yes"; then
-			{ { echo "$as_me:$LINENO: error: Linux-NTFS Gnome VFS module requires glib-2.0 and gnome-vfs-module-2.0 librares." >&5
-echo "$as_me: error: Linux-NTFS Gnome VFS module requires glib-2.0 and gnome-vfs-module-2.0 librares." >&2;}
+			{ { echo "$as_me:$LINENO: error: Linux-NTFS Gnome VFS module requires glib-2.0 and gnome-vfs-module-2.0 libraries." >&5
+echo "$as_me: error: Linux-NTFS Gnome VFS module requires glib-2.0 and gnome-vfs-module-2.0 libraries." >&2;}
    { (exit 1); exit 1; }; }
 		else
-			{ echo "$as_me:$LINENO: WARNING: Linux-NTFS Gnome VFS module requires glib-2.0 and gnome-vfs-module-2.0 librares." >&5
-echo "$as_me: WARNING: Linux-NTFS Gnome VFS module requires glib-2.0 and gnome-vfs-module-2.0 librares." >&2;}
+			{ echo "$as_me:$LINENO: WARNING: Linux-NTFS Gnome VFS module requires glib-2.0 and gnome-vfs-module-2.0 libraries." >&5
+echo "$as_me: WARNING: Linux-NTFS Gnome VFS module requires glib-2.0 and gnome-vfs-module-2.0 libraries." >&2;}
 		fi
 
   fi
